### ISSUE TITLE
Doesn't work with the letter "Ñ"

### ISSUE THREAD

**Issue by ClickHerexe** [petzku/Aegisub-Scripts#5] opened 2021-08-18 19:08 UTC
Failed to open D:\Mux\[├æ] 027.mkv.

[encode] no data written to target file
Exiting... (Interrupted by error)

PD. FIX: https://discord.com/channels/131816223523602432/710562732973490238/872225912387690527

**Comment by petzku** [comment] 2021-08-19 10:34
Duplicate of #2.

**Closed by petzku** 2021-08-19 10:34 UTC
